import type { Metadata } from 'next'
import '../styles/globals.css'
// import { AntdRegistry } from '@ant-design/nextjs-registry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body>
        {/* <AntdRegistry>{children}</AntdRegistry> */}
        {children}
      </body>
    </html>
  )
}
