import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { DarkMode } from "@/components/DarkMode/DarkMode";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <DarkMode />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
